# Stage 1: Build stage
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project to the working directory
COPY . .

# Build the application with Maven
RUN mvn clean package -DskipTests

# Stage 2: Runtime stage
FROM openjdk:17.0.1-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the build stage to the runtime stage
COPY --from=build /app/target/Buyfurn-0.0.1-SNAPSHOT.jar Buyfurn-backend.jar

# Expose port 8080
EXPOSE 8089

# Specify the command to run your application
ENTRYPOINT ["java", "-jar", "Buyfurn-backend.jar"]
